-- Drops CORRECTED from AttendanceResolution.
--
-- The owner ruled on 2026-08-07 that attendance records presence, not hours.
-- That removed the retroactive "when did you finish?" prompt, which was the
-- only thing that ever wrote this value — a forgotten session is now closed
-- as DISCARDED by the next punch-in instead.
--
-- Safe because no row can hold it: writing CORRECTED required a session left
-- open on an EARLIER app day, and the feature existed for under an hour.
-- Verified against the database before generating this. Note the USING cast
-- would fail the whole transaction loudly rather than corrupt anything if that
-- assumption were ever wrong, which is the failure mode to want.
--
-- Generated by `prisma migrate diff --from-config-datasource --to-schema`;
-- `migrate dev` could not be used because dropping an enum value needs an
-- interactive confirmation this environment cannot give.

-- AlterEnum
BEGIN;
CREATE TYPE "AttendanceResolution_new" AS ENUM ('PUNCH_OUT', 'DISCARDED');
ALTER TABLE "AttendanceSession" ALTER COLUMN "resolution" TYPE "AttendanceResolution_new" USING ("resolution"::text::"AttendanceResolution_new");
ALTER TYPE "AttendanceResolution" RENAME TO "AttendanceResolution_old";
ALTER TYPE "AttendanceResolution_new" RENAME TO "AttendanceResolution";
DROP TYPE "public"."AttendanceResolution_old";
COMMIT;
